# Generated by Django 6.0.4 on 2026-04-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('sheduled', 'Sheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=10)),
                ('Baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.baby')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
    ]
