# Generated by Django 6.0.4 on 2026-05-07 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_growthlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
