# Generated by Django 6.0.4 on 2026-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_remove_prescription_dosage_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='instructions',
            new_name='medicines',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
