# Generated by Django 6.0.4 on 2026-05-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_alter_growthlog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='baby',
            name='twins_group',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
