# Generated by Django 6.0.4 on 2026-05-14 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_baby_blood_group_baby_twins_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('observation', 'Observation'), ('symptom', 'Symptom'), ('reminder', 'Reminder'), ('feeding', 'Feeding'), ('sleep', 'Sleep'), ('milestone', 'Milestone'), ('other', 'Other')], default='observation', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('share_with_doctor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_notes', to=settings.AUTH_USER_MODEL)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_notes', to='parents.baby')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
