# Generated by Django 6.0.4 on 2026-05-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('vaccination', 'Vaccination'), ('nutrition', 'Nutrition'), ('development', 'Development'), ('emergency', 'Emergency')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
    ]
