# Generated by Django 6.0.4 on 2026-05-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional URL for an image cover', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube or Video URL', null=True),
        ),
    ]
