# Generated by Django 6.0.4 on 2026-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_image_url_resource_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='external_link',
            field=models.URLField(blank=True, help_text='Optional link to an external article or source', null=True),
        ),
    ]
