# Generated by Django 6.0.4 on 2026-05-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('private', 'Private'), ('testimonial', 'Testimonial')], default='private', max_length=20)),
                ('category', models.CharField(choices=[('doctor', 'Doctor'), ('platform', 'Platform'), ('clinic', 'Clinic'), ('suggestion', 'Suggestion')], max_length=30)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
